CREATE TABLE users (
  id TEXT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  email VARCHAR(254) NOT NULL,
  phone VARCHAR(20) NOT NULL DEFAULT '',
  landline VARCHAR(20) NOT NULL DEFAULT '',
  address VARCHAR(250) NOT NULL DEFAULT '',
  province VARCHAR(80) NOT NULL DEFAULT '',
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'customer',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_id_not_blank CHECK (BTRIM(id) <> ''),
  CONSTRAINT users_name_length CHECK (CHAR_LENGTH(BTRIM(name)) BETWEEN 2 AND 60),
  CONSTRAINT users_email_lowercase CHECK (email = LOWER(email)),
  CONSTRAINT users_email_not_blank CHECK (BTRIM(email) <> ''),
  CONSTRAINT users_password_not_blank CHECK (password_hash <> ''),
  CONSTRAINT users_role_valid CHECK (role IN ('admin', 'customer')),
  CONSTRAINT users_status_valid CHECK (status IN ('active', 'blocked')),
  CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  category VARCHAR(80) NOT NULL,
  brand VARCHAR(50) NOT NULL,
  price BIGINT NOT NULL,
  old_price BIGINT NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  rating NUMERIC(2, 1) NOT NULL DEFAULT 5,
  reviews INTEGER NOT NULL DEFAULT 0,
  discount INTEGER NOT NULL DEFAULT 0,
  badge VARCHAR(40) NOT NULL DEFAULT 'Mới',
  image VARCHAR(500) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT products_name_not_blank CHECK (BTRIM(name) <> ''),
  CONSTRAINT products_category_not_blank CHECK (BTRIM(category) <> ''),
  CONSTRAINT products_brand_not_blank CHECK (BTRIM(brand) <> ''),
  CONSTRAINT products_price_valid CHECK (price > 0 AND price <= 9007199254740991),
  CONSTRAINT products_old_price_valid CHECK (old_price >= price AND old_price <= 9007199254740991),
  CONSTRAINT products_stock_valid CHECK (stock >= 0),
  CONSTRAINT products_rating_valid CHECK (rating BETWEEN 0 AND 5),
  CONSTRAINT products_reviews_valid CHECK (reviews >= 0),
  CONSTRAINT products_discount_valid CHECK (discount BETWEEN 0 AND 100),
  CONSTRAINT products_image_not_blank CHECK (BTRIM(image) <> '')
);

CREATE TABLE orders (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  customer_name VARCHAR(60) NOT NULL,
  customer_email VARCHAR(254) NOT NULL,
  customer_phone VARCHAR(20) NOT NULL DEFAULT '',
  shipping_address VARCHAR(250) NOT NULL,
  total BIGINT NOT NULL,
  payment_method VARCHAR(20) NOT NULL DEFAULT 'sandbox',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT orders_id_not_blank CHECK (BTRIM(id) <> ''),
  CONSTRAINT orders_customer_name_not_blank CHECK (BTRIM(customer_name) <> ''),
  CONSTRAINT orders_customer_email_not_blank CHECK (BTRIM(customer_email) <> ''),
  CONSTRAINT orders_shipping_address_not_blank CHECK (BTRIM(shipping_address) <> ''),
  CONSTRAINT orders_total_valid CHECK (total >= 0 AND total <= 9007199254740991),
  CONSTRAINT orders_payment_method_valid CHECK (payment_method IN ('cod', 'sandbox')),
  CONSTRAINT orders_status_valid CHECK (status IN ('pending', 'confirmed', 'processing', 'shipping', 'delivered', 'cancelled')),
  CONSTRAINT orders_updated_after_created CHECK (updated_at >= created_at)
);

CREATE TABLE order_items (
  order_id TEXT NOT NULL REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  line_number SMALLINT NOT NULL,
  product_id INTEGER REFERENCES products(id) ON UPDATE CASCADE ON DELETE SET NULL,
  product_id_snapshot INTEGER NOT NULL,
  product_name VARCHAR(160) NOT NULL,
  product_image VARCHAR(500) NOT NULL,
  unit_price BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  PRIMARY KEY (order_id, line_number),
  CONSTRAINT order_items_line_number_valid CHECK (line_number > 0),
  CONSTRAINT order_items_product_id_snapshot_valid CHECK (product_id_snapshot > 0),
  CONSTRAINT order_items_product_name_not_blank CHECK (BTRIM(product_name) <> ''),
  CONSTRAINT order_items_product_image_not_blank CHECK (BTRIM(product_image) <> ''),
  CONSTRAINT order_items_unit_price_valid CHECK (unit_price > 0 AND unit_price <= 9007199254740991),
  CONSTRAINT order_items_quantity_valid CHECK (quantity > 0),
  CONSTRAINT order_items_product_once UNIQUE (order_id, product_id_snapshot)
);

CREATE INDEX users_role_status_idx ON users (role, status);
CREATE INDEX products_category_idx ON products (category);
CREATE INDEX products_stock_idx ON products (stock);
CREATE INDEX orders_user_created_at_idx ON orders (user_id, created_at DESC);
CREATE INDEX orders_created_at_idx ON orders (created_at DESC);
CREATE INDEX orders_status_idx ON orders (status);
CREATE INDEX order_items_product_id_idx ON order_items (product_id) WHERE product_id IS NOT NULL;
